//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gepa.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class pt_BR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal pt_BR() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gepa.Resources.Languages.pt-BR", typeof(pt_BR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Adicionar.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Adicionar Objetivo.
        /// </summary>
        internal static string AddClassGoal {
            get {
                return ResourceManager.GetString("AddClassGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Adicionar Conteúdo.
        /// </summary>
        internal static string AddContent {
            get {
                return ResourceManager.GetString("AddContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já é cadastrado? Faça o login.
        /// </summary>
        internal static string AlreadyRegisteredSignIn {
            get {
                return ResourceManager.GetString("AlreadyRegisteredSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Você tem certeza que deseja remover esse item?.
        /// </summary>
        internal static string AreYouSureYouWantToRemoveThisItem {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToRemoveThisItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Associe sua conta.
        /// </summary>
        internal static string AssociateYourAccount {
            get {
                return ResourceManager.GetString("AssociateYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Formas de associação.
        /// </summary>
        internal static string AssociationForms {
            get {
                return ResourceManager.GetString("AssociationForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cancelar.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Para inserir uma atividade, clique no botão &apos;Adicionar&apos;..
        /// </summary>
        internal static string ChorePlaceholder {
            get {
                return ResourceManager.GetString("ChorePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Atividades.
        /// </summary>
        internal static string Chores {
            get {
                return ResourceManager.GetString("Chores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Para inserir um objetivo, clique no botão &apos;Adicionar&apos;..
        /// </summary>
        internal static string ClassGoalPlaceholder {
            get {
                return ResourceManager.GetString("ClassGoalPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Plano de Aula.
        /// </summary>
        internal static string ClassPlan {
            get {
                return ResourceManager.GetString("ClassPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Confirmar senha.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Conecte-se com Facebook.
        /// </summary>
        internal static string ConnectFacebook {
            get {
                return ResourceManager.GetString("ConnectFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Conecte-se com Google.
        /// </summary>
        internal static string ConnectGoogle {
            get {
                return ResourceManager.GetString("ConnectGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Conteúdo.
        /// </summary>
        internal static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastro do Plano de Aula.
        /// </summary>
        internal static string CreateClassPlan {
            get {
                return ResourceManager.GetString("CreateClassPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Linguagem.
        /// </summary>
        internal static string CultureLanguage {
            get {
                return ResourceManager.GetString("CultureLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Descrição.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Divisão do conteúdo.
        /// </summary>
        internal static string DivisionOfContent {
            get {
                return ResourceManager.GetString("DivisionOfContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não tem cadastro ainda? Registre-se.
        /// </summary>
        internal static string DontHaveAccountYetDoRegister {
            get {
                return ResourceManager.GetString("DontHaveAccountYetDoRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Editar.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-mail.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email ou Nome de Usuário.
        /// </summary>
        internal static string EmailOrUserName {
            get {
                return ResourceManager.GetString("EmailOrUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Insira a {0}.
        /// </summary>
        internal static string EnterFieldValueFormatted {
            get {
                return ResourceManager.GetString("EnterFieldValueFormatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Insira o {0}.
        /// </summary>
        internal static string EnterFieldValueFormatted2 {
            get {
                return ResourceManager.GetString("EnterFieldValueFormatted2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Insira as {0}.
        /// </summary>
        internal static string EnterFieldValueFormatted3 {
            get {
                return ResourceManager.GetString("EnterFieldValueFormatted3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Informe seu endereço de e-mail ou nome de usuário:.
        /// </summary>
        internal static string EnterYourEmailAddressOrUsername {
            get {
                return ResourceManager.GetString("EnterYourEmailAddressOrUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Informe sua senha:.
        /// </summary>
        internal static string EnterYourPassword {
            get {
                return ResourceManager.GetString("EnterYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Para inserir uma avaliação, clique no botão &apos;Adicionar&apos;..
        /// </summary>
        internal static string EvaluationPlaceholder {
            get {
                return ResourceManager.GetString("EvaluationPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Avaliações.
        /// </summary>
        internal static string Evaluations {
            get {
                return ResourceManager.GetString("Evaluations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Excluir.
        /// </summary>
        internal static string Exclude {
            get {
                return ResourceManager.GetString("Exclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Excluir atividade.
        /// </summary>
        internal static string ExcludeChore {
            get {
                return ResourceManager.GetString("ExcludeChore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Excluir objetivo.
        /// </summary>
        internal static string ExcludeClassGoal {
            get {
                return ResourceManager.GetString("ExcludeClassGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Excluir conteúdo.
        /// </summary>
        internal static string ExcludeContent {
            get {
                return ResourceManager.GetString("ExcludeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Excluir avaliação.
        /// </summary>
        internal static string ExcludeEvaluation {
            get {
                return ResourceManager.GetString("ExcludeEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Esqueceu sua senha?.
        /// </summary>
        internal static string ForgotYourPassword {
            get {
                return ResourceManager.GetString("ForgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Gepa.
        /// </summary>
        internal static string Gepa {
            get {
                return ResourceManager.GetString("Gepa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sair.
        /// </summary>
        internal static string GetOut {
            get {
                return ResourceManager.GetString("GetOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Objetivo.
        /// </summary>
        internal static string Goal {
            get {
                return ResourceManager.GetString("Goal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Objetivos.
        /// </summary>
        internal static string Goals {
            get {
                return ResourceManager.GetString("Goals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O e-mail ou nome de usuário e senha não correspondem, verifique se os campos foram preenchidos corretamente..
        /// </summary>
        internal static string InvalidLoginError {
            get {
                return ResourceManager.GetString("InvalidLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Objetivo concluído.
        /// </summary>
        internal static string IsCompletedGoal {
            get {
                return ResourceManager.GetString("IsCompletedGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Atividade concluída.
        /// </summary>
        internal static string IsCompletedTask {
            get {
                return ResourceManager.GetString("IsCompletedTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Para inserir um conteúdo, clique no botão &apos;Adicionar&apos;..
        /// </summary>
        internal static string LessonContentPlaceholder {
            get {
                return ResourceManager.GetString("LessonContentPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha de logon.
        /// </summary>
        internal static string LogonFailure {
            get {
                return ResourceManager.GetString("LogonFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha ao fazer logon no serviço..
        /// </summary>
        internal static string LogonFailureMessage {
            get {
                return ResourceManager.GetString("LogonFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha pode estar incorreta..
        /// </summary>
        internal static string MaybeThePasswordBeIncorrectError {
            get {
                return ResourceManager.GetString("MaybeThePasswordBeIncorrectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Talvez o e-mail ou nome de usuário não exista..
        /// </summary>
        internal static string MaybeTheUserNameDoesNotExistError {
            get {
                return ResourceManager.GetString("MaybeTheUserNameDoesNotExistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Metodologia.
        /// </summary>
        internal static string Methodology {
            get {
                return ResourceManager.GetString("Methodology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não há planos de aula cadastrados ainda.
        /// </summary>
        internal static string NoClassPlanSaved {
            get {
                return ResourceManager.GetString("NoClassPlanSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum item selecionado!.
        /// </summary>
        internal static string NoItemSelected {
            get {
                return ResourceManager.GetString("NoItemSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não há conteúdo selecionado!.
        /// </summary>
        internal static string NoLessonContentSelected {
            get {
                return ResourceManager.GetString("NoLessonContentSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Observações.
        /// </summary>
        internal static string Observations {
            get {
                return ResourceManager.GetString("Observations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a OK.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A {0} deve ter no mínimo {2} caracteres..
        /// </summary>
        internal static string PasswordWithInvalidSizeErrorMessage {
            get {
                return ResourceManager.GetString("PasswordWithInvalidSizeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Português (Brasil).
        /// </summary>
        internal static string PtBR {
            get {
                return ResourceManager.GetString("PtBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registre-se.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastrar.
        /// </summary>
        internal static string Register2 {
            get {
                return ResourceManager.GetString("Register2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastrar plano de aula.
        /// </summary>
        internal static string RegisterClassPlan {
            get {
                return ResourceManager.GetString("RegisterClassPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Salvar.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Selecione um conteúdo para continuar a operação desejada..
        /// </summary>
        internal static string SelectContentToContinueOperationMessage {
            get {
                return ResourceManager.GetString("SelectContentToContinueOperationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Selecione a data.
        /// </summary>
        internal static string SelectTheDate {
            get {
                return ResourceManager.GetString("SelectTheDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Disciplina.
        /// </summary>
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Você se autenticou com êxito com &lt;strong&gt;{0}&lt;/strong&gt;. Insira um nome de usuário para este site abaixo e clique no botão Registrar para concluir o login..
        /// </summary>
        internal static string SuccessfulAuthenticationMessage {
            get {
                return ResourceManager.GetString("SuccessfulAuthenticationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Configurações do professor.
        /// </summary>
        internal static string TeacherSettings {
            get {
                return ResourceManager.GetString("TeacherSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Título.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome de usuário.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha e a senha de confirmação não correspondem..
        /// </summary>
        internal static string VerificationPasswordDoesNotMatchErrorMessage {
            get {
                return ResourceManager.GetString("VerificationPasswordDoesNotMatchErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bem-vindo, {0}.
        /// </summary>
        internal static string WelComeUserMessage {
            get {
                return ResourceManager.GetString("WelComeUserMessage", resourceCulture);
            }
        }
    }
}
