// <auto-generated />
namespace Gepa.Entities.Framework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddClassPlanSubject : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddClassPlanSubject));
        
        string IMigrationMetadata.Id
        {
            get { return "201810120020146_AddClassPlanSubject"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
